### ISSUE TITLE
JavaScript test install error in CI

### ISSUE THREAD

**Issue by Shelob9** [Shelob9/wordpress-plugin#3]
Tests run fine on my machine -- Windows 10 -- but do not install properly in Github actions. I think Windows vs Ubuntu is the issue here.

https://github.com/Shelob9/wordpress-plugin/runs/1413111730?check_suite_focus=true
```
ERR! stack Error: Failed to execute '/usr/local/bin/node /home/runner/work/wordpress-plugin/wordpress-plugin/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/runner/work/wordpress-plugin/wordpress-plugin/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/runner/work/wordpress-plugin/wordpress-plugin/node_modules/nodegit/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/runner/work/wordpress-plugin/wordpress-plugin/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR!
stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR!
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp
ERR! System Linux 5.4.0-1031-azure
node-pre-gyp ERR!
command "/usr/local/bin/node" "/home/runner/work/wordpress-plugin/wordpress-plugin/node_modules/nodegit/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
```

**Comment by Shelob9** [comment]
Close via c220aae500b49fed2e111a6d6da4fe4ee4dab9c4
